import type { WorkspaceData } from "./types";

export const workspaceData: WorkspaceData = {
  article: {
    fileName: "AI时代的判断力.md",
    updatedAt: "14:23",
    wordCount: 3284,
    title: "在算法替你思考之前，先把判断力留下来",
    rawText: `# 在算法替你思考之前，先把判断力留下来

写给在 AI 工具丛林里有点迷路的内容创作者。这不是一篇关于「怎么用 AI」的文章，是关于「怎么不被 AI 用掉」的笔记。

## 一、信息过载时代，判断力比知识更稀缺

过去十年我们以为最值钱的是知识，现在发现真正稀缺的是**在一堆都对的答案里，挑出最适合此刻的那一个**的能力。

> 提示词不是工作，提问才是。创作者的护城河，正在向「问什么」迁移。

## 二、AI 给的是答案，编辑要的是问题

AI 可以把表达变得更顺，但也可能把判断磨平。越是高效的时候，越要警惕自己是不是只是在顺着工具走。

## 三、三个练习：把判断力的肌肉养回来

1. 每天 20 分钟不被推荐流喂养
2. 把「我觉得」放回文章里
3. 保留一份不发布的写作

## 四、把「我觉得」重新放进文章里

AI 写得越像范文，越要敢于不工整。判断力的痕迹，就在那些不够圆润的地方。`,
  },
  parsedMarkdown: {
    status: "parsed",
    structure: {
      headings: 1,
      subheadings: 6,
      bolds: 14,
      quotes: 3,
      lists: 4,
    },
    structureTags: ["1 标题", "6 小标题", "14 加粗", "3 引用"],
  },
  analysis: {
    imageGenerationSource: {
      contentKind: "full-article-text",
      strategy: "直接将全文交给大模型，由模型自动拆成 4 张知识卡片并生成每张图的视觉方案",
    },
    cardOutlineTitles: [
      "信息过载时代，判断力比知识更稀缺",
      "AI 给的是答案，编辑要的是问题",
      "三个练习：每天留 20 分钟「不被喂养」的时间",
      "把「我觉得」重新放进文章里",
    ],
    keyQuotes: [
      "提示词不是工作，提问才是。",
      "AI 写得越像范文，越要敢于不工整。",
      "把判断的肌肉，每天养 20 分钟。",
    ],
    coverTheme: {
      title: "判断力 · 在算法之外",
      keywords: "判断力 / 信息筛选 / 提问 / 编辑视角",
    },
  },
  cardPlan: [
    {
      index: 1,
      title: "信息过载时代，判断力比知识更稀缺",
      summary: "当所有人都能获取同样的资料，谁能筛掉噪音，谁就掌握了下一层级的话语权。",
    },
    {
      index: 2,
      title: "AI 给的是答案，编辑要的是问题",
      summary: "提示词不是工作，提问才是。创作者的护城河，正在向「问什么」迁移。",
    },
    {
      index: 3,
      title: "三个练习：每天留 20 分钟「不被喂养」的时间",
      summary: "不刷推荐流，不看热搜榜，只读一段自己挑的文字 —— 把判断的肌肉养回来。",
    },
    {
      index: 4,
      title: "把「我觉得」重新放进文章里",
      summary: "AI 写得越像范文，越要敢于不工整。判断力的痕迹，就在那些不够圆润的地方。",
    },
  ],
  workflowStages: [
    { key: "upload", label: "原稿上传", status: "success", detail: "Markdown 文件已读取" },
    { key: "markdownParse", label: "Markdown 解析", status: "success", detail: "标题、引用、列表等结构已识别" },
    { key: "contentAnalysis", label: "内容拆解", status: "success", detail: "已拆为 4 张卡片，并提炼金句与封面主题" },
    { key: "imageGeneration", label: "图片生成", status: "failed", detail: "4 张卡片中 1 张生成失败，可局部重试", retryable: true },
    { key: "layoutGeneration", label: "排版生成", status: "success", detail: "公众号正文预览已生成，并完成插图位编排" },
    { key: "draftSync", label: "草稿同步", status: "success", detail: "公众号草稿已创建，可继续重新同步或打开草稿" },
  ],
  outputToggles: [
    { key: "knowledgeCards", label: "生成知识卡片", hint: "4 张", enabled: true },
    { key: "wechatCover", label: "生成公众号封面", hint: "2.35 : 1", enabled: true },
    { key: "xiaohongshuCover", label: "生成小红书封面", hint: "3 : 4", enabled: true },
  ],
  cardSize: {
    ratio: "3:4",
    width: 1536,
    height: 2048,
    ratioOptions: ["3:4", "4:3", "1:1", "9:16"],
  },
  styleAssets: [
    {
      name: "墨予镜 · 手绘知识卡",
      desc: "纸感底纹 / 手写线条",
      palette: ["#f3ecdb", "#1f3a36", "#b86b3a", "#8a8270"],
      meta: "v2.3 · 用过 18 次",
      pinned: true,
    },
    {
      name: "墨予镜 · 克制留白版",
      desc: "大量留白 / 细衬线标题",
      palette: ["#fbfaf6", "#222222", "#a59f8e", "#d4ccb8"],
      meta: "v1.4 · 用过 9 次",
    },
    {
      name: "墨予镜 · 深色观点版",
      desc: "深底高对比 / 金句视觉化",
      palette: ["#1f2422", "#e9e2cf", "#c9a567", "#3b3f3c"],
      meta: "v1.1 · 用过 6 次",
    },
    {
      name: "内容实验室 · 信息图版",
      desc: "结构化排版 / 数据要点",
      palette: ["#eef2ee", "#15543f", "#3b6fb1", "#c2cec4"],
      meta: "v0.9 · 用过 3 次",
    },
  ],
  layoutThemes: [
    {
      name: "墨予镜 · 留白长文版",
      desc: "白底长文 / 细衬线标题 / 克制强调",
      meta: "公众号主题 · A01",
      previewPalette: ["#f4f0e8", "#ffffff", "#2a2a2a", "#b7aa92"],
      shellBg: "#f4f0e8",
      articleBg: "#ffffff",
      titleColor: "#1f1f1f",
      headingColor: "#2a2a2a",
      bodyColor: "#3d3d3d",
      mutedColor: "#8d816f",
      quoteBg: "#f7f2e9",
      quoteBorder: "#a58352",
      ctaBg: "#2a2a2a",
      ctaText: "#ffffff",
      figureBg: "#efe7da",
      placeholderBg: "#faf6ef",
      placeholderBorder: "#d7ccb7",
      pinned: true,
    },
    {
      name: "内容实验室 · 结构阅读版",
      desc: "冷静信息感 / 分节更清楚 / 适合方法文",
      meta: "公众号主题 · B02",
      previewPalette: ["#edf3f0", "#ffffff", "#1c5143", "#9eb5ad"],
      shellBg: "#edf3f0",
      articleBg: "#ffffff",
      titleColor: "#173f35",
      headingColor: "#1c5143",
      bodyColor: "#30413c",
      mutedColor: "#71867f",
      quoteBg: "#f1f7f4",
      quoteBorder: "#1c5143",
      ctaBg: "#1c5143",
      ctaText: "#ffffff",
      figureBg: "#e4efe9",
      placeholderBg: "#f7fbf9",
      placeholderBorder: "#bdd0c9",
    },
    {
      name: "墨予镜 · 深墨专栏版",
      desc: "低饱和深墨 / 更强专栏感 / 适合观点文",
      meta: "公众号主题 · C01",
      previewPalette: ["#ece6df", "#fffdf9", "#2f332f", "#a59684"],
      shellBg: "#ece6df",
      articleBg: "#fffdf9",
      titleColor: "#252825",
      headingColor: "#2f332f",
      bodyColor: "#3c403c",
      mutedColor: "#867a6d",
      quoteBg: "#f4efe8",
      quoteBorder: "#2f332f",
      ctaBg: "#2f332f",
      ctaText: "#ffffff",
      figureBg: "#e8ded2",
      placeholderBg: "#f8f3ec",
      placeholderBorder: "#d2c5b6",
    },
  ],
  styleSelections: {
    knowledgeCards: 0,
    wechatInlineImages: 1,
    wechatLayout: 1,
    wechatCover: 2,
    xiaohongshuCover: 0,
  },
  generation: {
    generatedAt: "14:31",
    cardsCount: 4,
    coversCount: 2,
    layoutStatus: "已生成",
    summaryMeta: [
      { label: "知识卡片", value: "4 张" },
      { label: "封面", value: "2 张" },
      { label: "排版", value: "已生成", emerald: true },
      { label: "生成时间", value: "14:31" },
    ],
  },
  knowledgeCards: [
    {
      n: "01",
      title: "信息过载时代，判断力比知识更稀缺",
      summary: "当所有人都能获取同样的资料，谁能筛掉噪音，谁就掌握了下一层级的话语权。",
      composition: "暖米色纸面 / 手绘箭头 / 主标题居中偏上 / 留白底部 30%",
      img: "https://images.unsplash.com/photo-1686806372785-fcfe9efa9b70?w=900&q=80",
      state: "ok",
      provider: "mock",
    },
    {
      n: "02",
      title: "AI 给的是答案，编辑要的是问题",
      summary: "提示词不是工作，提问才是。创作者的护城河，正在向「问什么」迁移。",
      composition: "深墨绿底 / 米白衬线大字 / 引号装饰 / 右下作者签名印",
      img: "https://images.unsplash.com/photo-1760840415409-bf4b6b14988e?w=900&q=80",
      state: "ok",
      provider: "mock",
    },
    {
      n: "03",
      title: "三个练习：每天留 20 分钟「不被喂养」的时间",
      summary: "不刷推荐流，不看热搜榜，只读一段自己挑的文字 —— 把判断的肌肉养回来。",
      composition: "列表式构图 / 三栏编号 / 衬线小标题 / 卡片底部页脚条",
      img: "",
      state: "failed",
      provider: "mock",
    },
    {
      n: "04",
      title: "把「我觉得」重新放进文章里",
      summary: "AI 写得越像范文，越要敢于不工整。判断力的痕迹，就在那些不够圆润的地方。",
      composition: "纸质纹理 / 手写下划线 / 段落式版面 / 关键词以橙朱标记",
      img: "https://images.unsplash.com/photo-1778664305516-8243da9c2098?w=900&q=80",
      state: "ok",
      provider: "mock",
    },
  ],
  wechatInlineImages: [
    {
      id: "inline-01",
      placementLabel: "图片位 #1",
      sectionHeading: "信息过载时代，判断力比知识更稀缺",
      sectionType: "concept",
      sectionTheme: "信息过载时代，判断力比知识更稀缺",
      sectionKeywords: ["判断力", "筛选", "留白", "编辑视角"],
      sectionSummary: "当所有人都能获取同样的资料，谁能筛掉噪音，谁就掌握了下一层级的话语权。",
      visualDirection: "围绕判断力与筛选做抽象概念意象图，安静、克制、有人文思考感。",
      rationale: "用于承接第一节主观点，在首个论点段后插入，避免开头信息密度过高。",
      ratio: "16:9",
      width: 1536,
      height: 864,
      img: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=1400&q=80",
      state: "ok",
      provider: "mock",
    },
    {
      id: "inline-02",
      placementLabel: "图片位 #2",
      sectionHeading: "AI 给的是答案，编辑要的是问题",
      sectionType: "quote",
      sectionTheme: "AI 给的是答案，编辑要的是问题",
      sectionKeywords: ["提问", "编辑", "问题意识"],
      sectionSummary: "提示词不是工作，提问才是。创作者的护城河，正在向「问什么」迁移。",
      sectionQuote: "提示词不是工作，提问才是。",
      visualDirection: "围绕提问与编辑意识做轻观点感的杂志内页式配图。",
      rationale: "与金句形成并列强化，适合放在引用块后承接观点转折。",
      ratio: "16:9",
      width: 1536,
      height: 864,
      img: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=1400&q=80",
      state: "ok",
      provider: "mock",
    },
    {
      id: "inline-03",
      placementLabel: "图片位 #3",
      sectionHeading: "三个练习：每天留 20 分钟「不被喂养」的时间",
      sectionType: "method",
      sectionTheme: "三个练习：每天留 20 分钟「不被喂养」的时间",
      sectionKeywords: ["练习", "节奏", "结构感"],
      sectionSummary: "不刷推荐流，不看热搜榜，只读一段自己挑的文字 —— 把判断的肌肉养回来。",
      visualDirection: "围绕方法感、结构感和秩序感表达，不做步骤罗列。",
      rationale: "对应方法段落，帮助长列表内容中段换气。",
      ratio: "16:9",
      width: 1536,
      height: 864,
      img: "",
      state: "failed",
      provider: "mock",
    },
    {
      id: "inline-04",
      placementLabel: "图片位 #4",
      sectionHeading: "把「我觉得」重新放进文章里",
      sectionType: "transition",
      sectionTheme: "把「我觉得」重新放进文章里",
      sectionKeywords: ["表达", "留白", "作者判断"],
      sectionSummary: "AI 写得越像范文，越要敢于不工整。判断力的痕迹，就在那些不够圆润的地方。",
      visualDirection: "围绕表达与留白做阅读换气图，强调停顿感和轻情绪。",
      rationale: "放在文章后段，用于强调作者判断与全文收束。",
      ratio: "16:9",
      width: 1536,
      height: 864,
      img: "https://images.unsplash.com/photo-1517842645767-c639042777db?w=1400&q=80",
      state: "ok",
      provider: "mock",
    },
  ],
  covers: [
    {
      key: "wechatCover",
      label: "公众号封面",
      ratio: "2.35 : 1",
      status: "已生成 · v2",
      img: "https://images.unsplash.com/photo-1714636608872-048fc9231892?w=1400&q=80",
      state: "ok",
      provider: "mock",
      wide: true,
    },
    {
      key: "xiaohongshuCover",
      label: "小红书封面",
      ratio: "3 : 4",
      status: "已生成 · v1",
      img: "https://images.unsplash.com/photo-1646600950096-0489e2a461cc?w=900&q=80",
      state: "ok",
      provider: "mock",
    },
  ],
  draftReview: {
    readyTitle: "可同步到草稿箱",
    readyDescription: "系统已完成结构继承、重点识别和插图位编排",
    reviewChecks: [
      { title: "Markdown 结构", detail: "6 H2 · 3 引用 · 4 列表已保留", status: "pass" },
      { title: "重点句识别", detail: "3 处金句已强调", status: "pass" },
      { title: "插图位编排", detail: "系统已决定 4 处插图位置", status: "pass" },
      { title: "公众号格式", detail: "标题、首图、摘要合规", status: "pass" },
    ],
    syncStatus: [
      { label: "正文排版", note: "Markdown 已转为公众号 HTML · 6 段落" },
      { label: "卡片素材上传", note: "4 张 · 上传至素材库「2026-06」" },
      { label: "封面上传", note: "公众号封面 v2 · 小红书封面 v1" },
      { label: "草稿创建", note: "draft_id: msg_8c91a · 公众号后台可见" },
    ],
    imagePlacements: [
      {
        imageId: "inline-01",
        placementLabel: "图片位 #1",
        sectionHeading: "信息过载时代，判断力比知识更稀缺",
        anchorText: "一 · 信息过载时代，判断力比知识更稀缺",
        rationale: "用于承接第一节主观点，在首个论点段后插入，避免开头信息密度过高。",
        sectionType: "concept",
      },
      {
        imageId: "inline-02",
        placementLabel: "图片位 #2",
        sectionHeading: "AI 给的是答案，编辑要的是问题",
        anchorText: "提示词不是工作，提问才是。",
        rationale: "与金句形成并列强化，适合放在引用块后承接观点转折。",
        sectionType: "quote",
      },
      {
        imageId: "inline-03",
        placementLabel: "图片位 #3",
        sectionHeading: "三个练习：每天留 20 分钟「不被喂养」的时间",
        anchorText: "三个练习：把判断力的肌肉养回来",
        rationale: "对应方法段落，帮助长列表内容中段换气。",
        sectionType: "method",
      },
      {
        imageId: "inline-04",
        placementLabel: "图片位 #4",
        sectionHeading: "把「我觉得」重新放进文章里",
        anchorText: "把「我觉得」放回文章里",
        rationale: "放在文章后段，用于强调作者判断与全文收束。",
        sectionType: "transition",
      },
    ],
    preview: {
      title: "在算法替你思考之前，先把判断力留下来",
      accountName: "墨予镜",
      publishDate: "2026年6月7日",
      intro: "写给在 AI 工具丛林里有点迷路的内容创作者。这不是一篇关于「怎么用 AI」的文章，是关于「怎么不被 AI 用掉」的笔记。",
      blocks: [
        { type: "heading2", text: "一、信息过载时代，判断力比知识更稀缺" },
        { type: "paragraph", text: "过去十年我们以为最值钱的是知识，现在发现真正稀缺的是在一堆都对的答案里，挑出最适合此刻的那一个的能力。" },
        { type: "image", imageId: "inline-01", placementLabel: "图片位 #1", caption: "一 · 信息过载时代，判断力比知识更稀缺" },
        { type: "blockquote", text: "提示词不是工作，提问才是。创作者的护城河，正在向「问什么」迁移。" },
        { type: "heading2", text: "二、AI 给的是答案，编辑要的是问题" },
        { type: "paragraph", text: "AI 可以把表达变得更顺，但也可能把判断磨平。越是高效的时候，越要警惕自己是不是只是在顺着工具走。" },
        { type: "image", imageId: "inline-02", placementLabel: "图片位 #2", caption: "AI 给的是答案，编辑要的是问题" },
        { type: "heading2", text: "三、三个练习：把判断力的肌肉养回来" },
        { type: "ordered-list", items: ["每天 20 分钟不被推荐流喂养", "把「我觉得」放回文章里", "保留一份不发布的写作"] },
        { type: "image", imageId: "inline-03", placementLabel: "图片位 #3", caption: "三个练习：把判断力的肌肉养回来" },
        { type: "heading2", text: "四、把「我觉得」重新放进文章里" },
        { type: "paragraph", text: "AI 写得越像范文，越要敢于不工整。判断力的痕迹，就在那些不够圆润的地方。" },
        { type: "image", imageId: "inline-04", placementLabel: "图片位 #4", caption: "把「我觉得」重新放进文章里" },
        { type: "cta", title: "如果这段文字让你停了一下，欢迎留言告诉我", buttonText: "点亮「在看」 · 分享给同样在思考的人" },
      ],
    },
    editorHtml: "<section data-tool=\"content-matrix\"><p>mock html</p></section>",
  },
};
