import type { EntryBindingResolution, ModelCatalogResponse, ModelEntry, RelayAccessSummary } from "@/lib/schemas";

export type MockState = {
  models: ModelEntry[];
  entries: EntryBindingResolution[];
  relayAccess: RelayAccessSummary;
  catalogs: Record<string, ModelCatalogResponse>;
};

export function createMockState(): MockState {
  const models: ModelEntry[] = [
    {
      id: "preset-ppchat-relay",
      name: "PPChat 中转",
      providerLabel: "code.ppchat.vip",
      kind: "coding-plan",
      source: "preset",
      baseUrl: "https://code.ppchat.vip/v1",
      modelId: "gpt-5",
      reasoningEffort: "high",
      catalogFamily: "openai-compatible",
      purchaseUrl: "https://code.ppchat.vip/",
      status: "active",
      statusNote: "已测试通过，可直接绑定编码入口。",
      hasStoredApiKey: true,
      maskedApiKey: "sk-ppc...demo",
      lastTestedAt: "2026-05-02 10:20",
      lastTestResult: "success",
      lastTestCode: "ok",
      lastTestMessage: "Responses 与 chat 都可用。",
      capabilities: {
        responses: { ok: true, streamOk: true },
        chatCompletions: { ok: true },
        lastProbedAt: "2026-05-02 10:20",
        lastErrorMessage: null,
      },
      presetPriority: "recommended-first",
      recommendedTaskCategories: ["通用工具"],
      recommendedTaskIds: ["task-codex-repo"],
      selectionReason: "适合作为默认编码工作流模型。",
      activationHint: "已经可用。",
      costTier: "中",
      capabilityTags: ["编码", "长上下文"],
      tags: ["中转 API", "Coding Plan"],
    },
    {
      id: "preset-qwen-max",
      name: "Qwen Max 官方",
      providerLabel: "阿里云百炼",
      kind: "domestic-model",
      source: "preset",
      baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
      modelId: "qwen-max",
      reasoningEffort: null,
      catalogFamily: "openai-compatible",
      purchaseUrl: "https://bailian.console.aliyun.com/",
      status: "configured-pending-test",
      statusNote: "已配置待测试。",
      hasStoredApiKey: true,
      maskedApiKey: "sk-qwe...demo",
      lastTestedAt: "2026-05-01 23:10",
      lastTestResult: "idle",
      lastTestCode: "not-tested",
      lastTestMessage: "等待手动测试。",
      capabilities: {
        responses: { ok: false, streamOk: false },
        chatCompletions: { ok: true },
        lastProbedAt: "2026-05-01 23:10",
        lastErrorMessage: null,
      },
      presetPriority: "recommended",
      recommendedTaskCategories: ["业务任务"],
      recommendedTaskIds: ["task-therapy-dialogue"],
      selectionReason: "适合作为正式业务候选。",
      activationHint: "继续测试连接。",
      costTier: "高",
      capabilityTags: ["对话", "国产模型"],
      tags: ["国产模型", "正式生产候选"],
    },
    {
      id: "custom-claude-sonnet",
      name: "Claude Sonnet 自建",
      providerLabel: "自建中转",
      kind: "relay-api",
      source: "custom",
      baseUrl: "https://relay.example.com/v1",
      modelId: "claude-sonnet-4",
      reasoningEffort: "medium",
      catalogFamily: "openai-compatible",
      purchaseUrl: "https://relay.example.com/dashboard",
      status: "test-failed",
      statusNote: "流式探测失败，暂不建议给 Codex 使用。",
      hasStoredApiKey: false,
      maskedApiKey: null,
      lastTestedAt: "2026-05-02 09:40",
      lastTestResult: "failed",
      lastTestCode: "stream-failed",
      lastTestMessage: "流式接口失败。",
      capabilities: {
        responses: { ok: true, streamOk: false },
        chatCompletions: { ok: true },
        lastProbedAt: "2026-05-02 09:40",
        lastErrorMessage: "stream failed",
      },
      presetPriority: null,
      recommendedTaskCategories: [],
      recommendedTaskIds: [],
      selectionReason: null,
      activationHint: "补齐兼容性。",
      costTier: "中",
      capabilityTags: ["relay"],
      tags: ["自定义"],
    },
  ];

  const resolvedModel = models[0];

  const entries: EntryBindingResolution[] = [
    {
      entryId: "entry-codex-ide-local",
      alias: "relayhub-entry-codex-local",
      clientFamily: "codex",
      adapterType: "codex_local",
      hostType: "mac",
      protocolFamily: "openai-responses",
      controllable: true,
      defaultModelEntryId: resolvedModel.id,
      fallbackModelEntryId: null,
      reasoningEffortOverride: "medium",
      effectiveReasoningEffort: "medium",
      statusNote: "当前给 Codex 本机工作流使用。",
      usageEvidence: {
        lastSuccessfulRequestAt: "2026-05-02T11:18:00.000Z",
        lastSuccessfulRequestId: "req-codex-1",
        lastSuccessfulRoute: "/v1/responses",
        lastSuccessfulModelEntryId: resolvedModel.id,
      },
      resolvedModel: {
        id: resolvedModel.id,
        name: resolvedModel.name,
        baseUrl: resolvedModel.baseUrl,
        modelId: resolvedModel.modelId,
        reasoningEffort: resolvedModel.reasoningEffort,
        status: resolvedModel.status,
        hasStoredApiKey: resolvedModel.hasStoredApiKey,
      },
    },
    {
      entryId: "entry-paperclip-claude-local-server",
      alias: "relayhub-entry-paperclip-claude-local-server",
      clientFamily: "paperclip",
      adapterType: "claude_local",
      hostType: "server",
      protocolFamily: "anthropic-messages",
      controllable: true,
      defaultModelEntryId: "custom-claude-sonnet",
      fallbackModelEntryId: null,
      reasoningEffortOverride: null,
      effectiveReasoningEffort: "medium",
      statusNote: "Paperclip claude_local 统一入口。",
      usageEvidence: {
        lastSuccessfulRequestAt: null,
        lastSuccessfulRequestId: null,
        lastSuccessfulRoute: null,
        lastSuccessfulModelEntryId: null,
      },
      resolvedModel: {
        id: "custom-claude-sonnet",
        name: "Claude Sonnet 自建",
        baseUrl: "https://relay.example.com/v1",
        modelId: "claude-sonnet-4",
        reasoningEffort: "medium",
        status: "test-failed",
        hasStoredApiKey: false,
      },
    },
    {
      entryId: "entry-claude-mobile-observe",
      alias: "claude-mobile-observe",
      clientFamily: "claude",
      adapterType: null,
      hostType: "external-observe",
      protocolFamily: "observe-only",
      controllable: false,
      defaultModelEntryId: null,
      fallbackModelEntryId: null,
      reasoningEffortOverride: null,
      effectiveReasoningEffort: null,
      statusNote: "只做观测。",
      usageEvidence: null,
      resolvedModel: null,
    },
  ];

  return {
    models,
    entries,
    relayAccess: {
      hasStoredRelayToken: true,
      maskedRelayToken: "relay...prod",
      effectiveSource: "control-plane",
      updatedAt: "2026-05-02 11:00",
    },
    catalogs: {
      "custom-claude-sonnet": {
        items: [
          { id: "claude-sonnet-4", label: "Claude Sonnet 4" },
          { id: "claude-opus-4", label: "Claude Opus 4" },
        ],
        fetchedAt: "2026-05-02T11:00:00.000Z",
      },
    },
  };
}
